apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic-job.fullname" . }}-cronjob
  labels:
    {{- include "generic-job.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"  # Schedule for the CronJob
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "generic-job.labels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ .Chart.Name }}-job-container
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              env:
                {{- toYaml .Values.env | nindent 16 }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          restartPolicy: {{ .Values.restartPolicy }}