repositories:
  - name: "ingress-nginx"
    url: "https://kubernetes.github.io/ingress-nginx"

helmDefaults:
  cleanupOnFail: false
  createNamespace: true

releases:
  - name: "ingress-nginx"
    namespace: "ingress-nginx"
    chart: "ingress-nginx/ingress-nginx"
    version: "4.7.0"
    wait: true

    values:
      - controller:
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
            externalTrafficPolicy: Local
            loadBalancerSourceRanges:
              - "49.248.27.91/32"