name: Frontend CI

on:
  push:
    paths:
      - 'apps/frontend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'apps/frontend/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get last commit hash
        id: get_commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t devregistry1908.azurecr.io/frontend:${{ env.COMMIT_HASH }} ./apps/frontend

      - name: Push Docker image
        run: docker push devregistry1908.azurecr.io/frontend:${{ env.COMMIT_HASH }}
